[package]
name = "roguelikedev"
version = "0.1.0"
authors = ["Hunter Marshall <Beidah@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
tcod = "0.12.0"
specs = "0.11.2"
specs-derive = "0.4.0"
doryen-fov = "0.1.1"